using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace api.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Replaces legacy uuid time_slots/bookings with bigint slots/bookings (queue booking).
    /// Uses SQL only in Up() so we never rely on DropForeignKey with an EF-specific name — the legacy FK may be
    /// <c>FK_bookings_time_slots_slot_id</c> (EF) or <c>fk_bookings_time_slots_slot_id</c> (raw SQL migration).
    /// </summary>
    public partial class QueueBookingSlotsLongIds : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP INDEX IF EXISTS ix_bookings_slot_id;
                DROP TABLE IF EXISTS bookings CASCADE;
                DROP TABLE IF EXISTS time_slots CASCADE;
                DROP TABLE IF EXISTS slots CASCADE;

                CREATE TABLE slots (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    start_time timestamp with time zone NOT NULL,
                    end_time timestamp with time zone NOT NULL,
                    capacity integer NOT NULL,
                    booked_count integer NOT NULL DEFAULT 0,
                    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT chk_slots_booked_lte_capacity CHECK (booked_count <= capacity)
                );

                CREATE TABLE bookings (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    slot_id bigint NOT NULL,
                    patient_name character varying(500) NOT NULL,
                    status text NOT NULL,
                    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT chk_bookings_status CHECK (status IN ('ACTIVE', 'CANCELLED')),
                    CONSTRAINT "FK_bookings_slots_slot_id" FOREIGN KEY (slot_id) REFERENCES slots (id) ON DELETE RESTRICT
                );

                -- Idempotent: startup retries / partial runs can leave this index name behind while __EFMigrationsHistory has no row.
                DROP INDEX IF EXISTS ix_bookings_slot_id;
                CREATE INDEX ix_bookings_slot_id ON bookings (slot_id);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS bookings CASCADE;""");
            migrationBuilder.Sql("""DROP TABLE IF EXISTS slots CASCADE;""");

            migrationBuilder.CreateTable(
                name: "time_slots",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    start_time = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    end_time = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    capacity = table.Column<int>(type: "integer", nullable: false),
                    booked_count = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "NOW()")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_time_slots", x => x.id);
                    table.CheckConstraint("chk_time_slots_booked_count_range", "\"booked_count\" >= 0 AND \"booked_count\" <= \"capacity\"");
                    table.CheckConstraint("chk_time_slots_capacity_positive", "\"capacity\" > 0");
                    table.CheckConstraint("chk_time_slots_time_range", "\"end_time\" > \"start_time\"");
                });

            migrationBuilder.CreateTable(
                name: "bookings",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: true),
                    phone_number = table.Column<string>(type: "text", maxLength: 10, nullable: true),
                    slot_id = table.Column<Guid>(type: "uuid", nullable: false),
                    status = table.Column<string>(type: "text", nullable: false),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "NOW()")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_bookings", x => x.id);
                    table.CheckConstraint("chk_bookings_status", "status IN ('active', 'cancelled')");
                    table.CheckConstraint("chk_bookings_identity_required", "user_id IS NOT NULL OR phone_number IS NOT NULL");
                    table.CheckConstraint("chk_bookings_phone_format", "phone_number IS NULL OR phone_number ~ '^[0-9]{9,10}$'");
                    table.ForeignKey(
                        name: "FK_bookings_time_slots_slot_id",
                        column: x => x.slot_id,
                        principalTable: "time_slots",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_bookings_slot_id",
                table: "bookings",
                column: "slot_id");

            migrationBuilder.CreateIndex(
                name: "ux_bookings_phone_slot_active",
                table: "bookings",
                columns: new[] { "phone_number", "slot_id" },
                unique: true,
                filter: "\"status\" = 'active' AND phone_number IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ux_bookings_user_slot_active",
                table: "bookings",
                columns: new[] { "user_id", "slot_id" },
                unique: true,
                filter: "\"status\" = 'active' AND user_id IS NOT NULL");
        }
    }
}
